//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpertTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE ExpertTools;
        ///
        ///--Tables
        ///
        ///CREATE TABLE QueriesAnalyzeTlQueries
        ///(
        ///	id INT IDENTITY NOT NULL,
        ///	_Period DATETIME2 not null,
        ///	_user NVARCHAR(200) NOT NULL,
        ///	connectId NVARCHAR(20) NOT NULL,
        ///	clientId NVARCHAR(20) NOT NULL,
        ///	sql NVARCHAR(MAX) NOT NULL,
        ///	normalized_sql NVARCHAR(MAX) NOT NULL,
        ///	context_first_line NVARCHAR(400) NOT NULL,
        ///	context_last_line NVARCHAR(400) NOT NULL,
        ///	context_exists BIT NOT NULL,
        ///	_hash NVARCHAR(32) NOT NULL,
        ///	CONSTRAINT PK_QueriesAnalyzeTlQueries PRIMARY KEY(id)
        ///);
        ///
        ///CREATE TABLE Que [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	T1.id,
        ///	MIN(T2._Period) AS context_period
        ///INTO #j1
        ///FROM QueriesAnalyzeTlQueries AS T1
        ///	INNER JOIN QueriesAnalyzeTlContexts AS T2
        ///		ON T1._Period &lt; T2._Period
        ///		AND T1.clientId = T2.clientId
        ///		AND T1.connectId = T2.connectId
        ///WHERE
        ///	T1.context_exists = 0
        ///GROUP BY
        ///	T1.id;
        ///
        ///UPDATE QueriesAnalyzeTlQueries
        ///SET
        ///	QueriesAnalyzeTlQueries.context_first_line = T1.context_first_line,
        ///	QueriesAnalyzeTlQueries.context_last_line = T1.context_last_line,
        ///	QueriesAnalyzeTlQueries.context_exists = 1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FillContext {
            get {
                return ResourceManager.GetString("FillContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO QueriesAnalyzeAvgSqlQueries
        ///SELECT
        ///	SUM(duration) / COUNT(_hash),
        ///	SUM(physical_reads) / COUNT(_hash),
        ///	SUM(logical_reads) / COUNT(_hash),
        ///	SUM(writes) / COUNT(_hash),
        ///	SUM(cpu_time) / COUNT(_hash),
        ///	_hash
        ///FROM QueriesAnalyzeSqlQueries
        ///GROUP BY
        ///	_hash.
        /// </summary>
        internal static string FillQueriesAvg {
            get {
                return ResourceManager.GetString("FillQueriesAvg", resourceCulture);
            }
        }
    }
}
